# Generated by Django 5.1.6 on 2025-11-27 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycollections', '0004_collection_arttoy_id_collection_current_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='bottomMessage',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='topMessage',
        ),
    ]
